name: credibook_challange
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route: ^4.0.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter_mobx: ^2.0.6+1
  flutter_svg_provider: ^1.0.3
  intl: ^0.17.0
  mobx: ^2.0.7+2
  screenshot: ^1.2.3
  share_plus: ^4.0.7
  get_it: ^7.2.0
  freezed_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^4.0.0
  build_runner: ^2.1.11
  dio:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.0.7
  freezed:

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/

flutter_intl:
  enabled: true
  generate: true
  class_name: I10n
  arb_dir: lib/utils/i10n
  output_dir: lib/utils/i10n

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/png/credibook-logo.png"
